In [1]:
import os

from parse_vcf_clinvar import *

In [2]:
# parse_clinvar_vcf("/home/tesselle/clinvar/first_1000_lines_anno.vcf.gz")

In [3]:
parse_clinvar_vcf("data/snp_pat_lpat_clinvar_20250421_anno.vcf.gz")

In [4]:
import pandas as pd

In [5]:
df = pd.read_table("data/snp_pat_lpat_clinvar_20250421_anno.vcf.tsv")

/tmp/ipykernel_3176898/861176538.py:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_table("data/snp_pat_lpat_clinvar_20250421_anno.vcf.tsv")

In [6]:
df

,CHROM,POS,ID,REF,ALT,CLNREVSTAT,CLNSIG,CLNVC,GENEINFO,MC,...,Feature,BIOTYPE,cDNA_position,CDS_position,Protein_position,Amino_acids,Codons,STRAND,FLAGS,CANONICAL
0,chr1,943995,950448,C,T,"criteria_provided,_single_submitter",Pathogenic,single_nucleotide_variant,SAMD11:148398,SO:0001587|nonsense,...,ENST00000327044,protein_coding,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,YES
1,chr1,943995,950448,C,T,"criteria_provided,_single_submitter",Pathogenic,single_nucleotide_variant,SAMD11:148398,SO:0001587|nonsense,...,ENST00000341065,protein_coding,1611.0,1612.0,538.0,R/*,Cga/Tga,1.0,cds_start_NF,NaN
2,chr1,943995,950448,C,T,"criteria_provided,_single_submitter",Pathogenic,single_nucleotide_variant,SAMD11:148398,SO:0001587|nonsense,...,ENST00000342066,protein_coding,1978.0,1888.0,630.0,R/*,Cga/Tga,1.0,NaN,NaN
3,chr1,943995,950448,C,T,"criteria_provided,_single_submitter",Pathogenic,single_nucleotide_variant,SAMD11:148398,SO:0001587|nonsense,...,ENST00000455979,protein_coding,1467.0,1468.0,490.0,R/*,Cga/Tga,1.0,cds_start_NF,NaN
4,chr1,943995,950448,C,T,"criteria_provided,_single_submitter",Pathogenic,single_nucleotide_variant,SAMD11:148398,SO:0001587|nonsense,...,ENST00000464948,retained_intron,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2325098,chrMT,16002,690271,T,C,"criteria_provided,_multiple_submitters,_no_con...",Pathogenic/Likely_pathogenic,single_nucleotide_variant,MT-TP:4571,SO:0001583|missense_variant,...,ENST00000387449,Mt_tRNA,NaN,NaN,NaN,NaN,NaN,1.0,NaN,YES
2325099,chrMT,16002,690271,T,C,"criteria_provided,_multiple_submitters,_no_con...",Pathogenic/Likely_pathogenic,single_nucleotide_variant,MT-TP:4571,SO:0001583|missense_variant,...,ENST00000387456,Mt_tRNA,NaN,NaN,NaN,NaN,NaN,1.0,NaN,YES
2325100,chrMT,16002,690271,T,C,"criteria_provided,_multiple_submitters,_no_con...",Pathogenic/Likely_pathogenic,single_nucleotide_variant,MT-TP:4571,SO:0001583|missense_variant,...,ENST00000387459,Mt_tRNA,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,YES
2325101,chrMT,16002,690271,T,C,"criteria_provided,_multiple_submitters,_no_con...",Pathogenic/Likely_pathogenic,single_nucleotide_variant,MT-TP:4571,SO:0001583|missense_variant,...,ENST00000387460,Mt_tRNA,NaN,NaN,NaN,NaN,NaN,1.0,NaN,YES
2325102,chrMT,16002,690271,T,C,"criteria_provided,_multiple_submitters,_no_con...",Pathogenic/Likely_pathogenic,single_nucleotide_variant,MT-TP:4571,SO:0001583|missense_variant,...,ENST00000387461,Mt_tRNA,22.0,NaN,NaN,NaN,NaN,-1.0,NaN,YES

In [7]:
df['CANONICAL'].value_counts()

CANONICAL
YES    224079
Name: count, dtype: int64

In [8]:
df['Consequence'].value_counts()

Consequence
stop_gained                                                           327795
missense_variant                                                      276981
downstream_gene_variant                                               276204
upstream_gene_variant                                                 238832
non_coding_transcript_exon_variant                                    234959
                                                                       ...
splice_region_variant&stop_retained_variant&NMD_transcript_variant         7
stop_lost&splice_region_variant                                            6
splice_region_variant&stop_retained_variant                                3
stop_retained_variant                                                      3
intergenic_variant                                                         2
Name: count, Length: 65, dtype: int64

In [9]:
df["MC"].value_counts()

MC
SO:0001587|nonsense                                                                                                                                                          640235
SO:0001583|missense_variant                                                                                                                                                  518192
SO:0001575|splice_donor_variant                                                                                                                                              250644
SO:0001574|splice_acceptor_variant                                                                                                                                           208988
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant                                                                                                                 127216
                                                                                                                                                                              ...
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001819|synonymous_variant                                                                                                    11
SO:0001574|splice_acceptor_variant,SO:0001582|initiator_codon_variant,SO:0001583|missense_variant,SO:0001619|non-coding_transcript_variant,SO:0001623|5_prime_UTR_variant        10
SO:0001578|stop_lost,SO:0001587|nonsense                                                                                                                                          8
SO:0001619|non-coding_transcript_variant,SO:0001624|3_prime_UTR_variant,SO:0001627|intron_variant                                                                                 5
SO:0001574|splice_acceptor_variant,SO:0001582|initiator_codon_variant                                                                                                             2
Name: count, Length: 179, dtype: int64

In [11]:
filtered_df = df[(df['CANONICAL'] == 'YES') & df['Consequence'].str.contains('stop_gained', na=False)]

In [12]:
filtered_df['Consequence'].value_counts()

Consequence
stop_gained                          57206
stop_gained&splice_region_variant     2315
Name: count, dtype: int64

In [18]:
a = filtered_df[(filtered_df['Consequence'] == 'stop_gained&splice_region_variant')]

In [20]:
a

,CHROM,POS,ID,REF,ALT,CLNSIG,CLNVC,GENEINFO,MC,Consequence,...,Feature,BIOTYPE,cDNA_position,CDS_position,Protein_position,Amino_acids,Codons,STRAND,FLAGS,CANONICAL
80,chr1,1044111,1076092,G,T,Pathogenic,single_nucleotide_variant,AGRN:375790,SO:0001587|nonsense,stop_gained&splice_region_variant,...,ENST00000379370,protein_coding,2055.0,2002.0,668.0,E/*,Gag/Tag,1.0,NaN,YES
1428,chr1,1825399,1433729,G,A,Pathogenic,single_nucleotide_variant,GNB1:2782,"SO:0001587|nonsense,SO:0001623|5_prime_UTR_var...",stop_gained&splice_region_variant,...,ENST00000378609,protein_coding,418.0,55.0,19.0,R/*,Cga/Tga,-1.0,NaN,YES
2007,chr1,2408452,2677658,G,C,Likely_pathogenic,single_nucleotide_variant,PEX10:5192,SO:0001587|nonsense,stop_gained&splice_region_variant,...,ENST00000447513,protein_coding,662.0,600.0,200.0,Y/*,taC/taG,-1.0,NaN,YES
2882,chr1,5880114,1455063,G,A,Pathogenic,single_nucleotide_variant,NPHP4:261734,"SO:0001587|nonsense,SO:0001619|non-coding_tran...",stop_gained&splice_region_variant,...,ENST00000378156,protein_coding,2831.0,2611.0,871.0,R/*,Cga/Tga,-1.0,NaN,YES
3065,chr1,5967299,968316,G,A,Pathogenic,single_nucleotide_variant,NPHP4:261734,"SO:0001587|nonsense,SO:0001619|non-coding_tran...",stop_gained&splice_region_variant,...,ENST00000378156,protein_coding,737.0,517.0,173.0,Q/*,Caa/Taa,-1.0,NaN,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303883,chrX,154413567,638931,G,T,Pathogenic,single_nucleotide_variant,TAFAZZIN:6901,"SO:0001587|nonsense,SO:0001619|non-coding_tran...",stop_gained&splice_region_variant,...,ENST00000601016,protein_coding,675.0,370.0,124.0,G/*,Gga/Tga,1.0,NaN,YES
2304265,chrX,154419745,202093,G,A,Pathogenic,single_nucleotide_variant,TAFAZZIN:6901,"SO:0001587|nonsense,SO:0001619|non-coding_tran...",stop_gained&splice_region_variant,...,ENST00000601016,protein_coding,887.0,582.0,194.0,W/*,tgG/tgA,1.0,NaN,YES
2304303,chrX,154419746,559336,G,T,Pathogenic,single_nucleotide_variant,TAFAZZIN:6901,"SO:0001587|nonsense,SO:0001619|non-coding_tran...",stop_gained&splice_region_variant,...,ENST00000601016,protein_coding,888.0,583.0,195.0,G/*,Gga/Tga,1.0,NaN,YES
2304569,chrX,154420262,662186,C,T,Pathogenic,single_nucleotide_variant,TAFAZZIN:6901,"SO:0001587|nonsense,SO:0001619|non-coding_tran...",stop_gained&splice_region_variant,...,ENST00000601016,protein_coding,1002.0,697.0,233.0,Q/*,Cag/Tag,1.0,NaN,YES
2310243,chrX,154561782,426975,C,T,Pathogenic,single_nucleotide_variant,IKBKG:8517,"SO:0001587|nonsense,SO:0001619|non-coding_tran...",stop_gained&splice_region_variant,...,ENST00000594239,protein_coding,907.0,766.0,256.0,R/*,Cga/Tga,1.0,NaN,YES

In [19]:
a["MC"].value_counts()

MC
SO:0001587|nonsense                                                                                                                                  1724
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant                                                                                          238
SO:0001587|nonsense,SO:0001627|intron_variant                                                                                                         127
SO:0001587|nonsense,SO:0001623|5_prime_UTR_variant                                                                                                     60
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001627|intron_variant                                                                 37
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001623|5_prime_UTR_variant                                                            33
SO:0001587|nonsense,SO:0001623|5_prime_UTR_variant,SO:0001627|intron_variant                                                                           19
SO:0001583|missense_variant,SO:0001587|nonsense                                                                                                        12
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001623|5_prime_UTR_variant,SO:0001627|intron_variant                                  12
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant                                                                6
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001819|synonymous_variant                                                              5
SO:0001587|nonsense,SO:0001819|synonymous_variant                                                                                                       4
SO:0001587|nonsense,SO:0001624|3_prime_UTR_variant                                                                                                      4
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001627|intron_variant                                                                               2
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001623|5_prime_UTR_variant,SO:0001819|synonymous_variant                               2
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001623|5_prime_UTR_variant,SO:0001627|intron_variant       2
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001624|3_prime_UTR_variant                                                             2
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001819|synonymous_variant                                                                           1
SO:0001587|nonsense,SO:0001624|3_prime_UTR_variant,SO:0001627|intron_variant                                                                            1
SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001624|3_prime_UTR_variant,SO:0001627|intron_variant                                   1
SO:0001574|splice_acceptor_variant,SO:0001587|nonsense,SO:0001623|5_prime_UTR_variant                                                                   1
SO:0001575|splice_donor_variant,SO:0001627|intron_variant                                                                                               1
SO:0001587|nonsense,SO:0001623|5_prime_UTR_variant,SO:0002153|genic_upstream_transcript_variant                                                         1
SO:0001587|nonsense,SO:0001623|5_prime_UTR_variant,SO:0001819|synonymous_variant                                                                        1
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001624|3_prime_UTR_variant                                 1
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001819|synonymous_variant                                  1
SO:0001583|missense_variant,SO:0001587|nonsense,SO:0001619|non-coding_transcript_variant,SO:0001627|intron_variant,SO:0001819|synonymous_variant        1
Name: count, dtype: int64

In [13]:
filtered_df["CLNSIG"].value_counts()

CLNSIG
Pathogenic                       40183
Likely_pathogenic                11816
Pathogenic/Likely_pathogenic      7518
Pathogenic|other                     2
Pathogenic|risk_factor               1
Likely_pathogenic|risk_factor        1
Name: count, dtype: int64

In [14]:
filtered_df["CLNVC"].value_counts()

CLNVC
single_nucleotide_variant    59521
Name: count, dtype: int64

In [16]:
filtered_df["CLNSIG"].value_counts()

CLNSIG
Pathogenic                       40183
Likely_pathogenic                11816
Pathogenic/Likely_pathogenic      7518
Pathogenic|other                     2
Pathogenic|risk_factor               1
Likely_pathogenic|risk_factor        1
Name: count, dtype: int64